version: '3.9'
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - "./mongo_data:/data/db"
    restart: unless-stopped
    ports:
      - "27017:27017"
